### ISSUE TITLE
S3 Lens missing permissions

### ISSUE THREAD

**Issue by dverdonschot** [awslabs/aws-serverless-data-lake-framework#303]
**Describe the bug**
Tried to role out SDLF multi domain with S3 Storage lens enabled like described in the workshop.
Updated both the team-domain-team-dev.yaml and datasets.yaml file with s3 lens configuration.

https://catalog.us-east-1.prod.workshops.aws/workshops/501cb14c-91b3-455c-a2a9-d0a21ce68114/en-US/40-goodies/400-monitoring#s3-storage-lens

But when deploying the domain on a producer account it would fail with the below Error complaining that the S3 Lens group couldn't be created due to a permission issue.

Fixed it on our side by adding the following permissions to sdlf-cicd-domain policy that is enabled with monitoring:

File: template-cicd-domain-roles.yaml
Resource Updated: rMonitoringDomainCloudFormationPolicy:

```yaml
          # Added permission for S3 StorageLens
          - Effect: Allow
            Action:
              - s3:CreateStorageLensGroup
              - s3:UpdateStorageLensGroup
              - s3:GetStorageLensGroup
              - s3:ListStorageLensGroups
              - s3:DeleteStorageLensGroup
              - s3:TagResource
              - s3:UntagResource
              - s3:ListTagsForResource
            Resource: 
              - !Sub "arn:${AWS::Partition}:s3:${AWS::Region}:${AWS::AccountId}:storage-lens-group/sdlf-*"
```

Error when deploying Domain with S3 lens enabled.
```json
{
    "eventVersion": "1.09",
    "userIdentity": {
        "type": "AssumedRole",
        "principalId": ":AWSCloudFormation",
        "arn": "arn:aws:sts::1234567890:assumed-role/sdlf-cicd-domain/AWSCloudFormation",
        "accountId": "1234567890",
        "accessKeyId": "",
        "sessionContext": {
            "sessionIssuer": {
                "type": "Role",
                "principalId": "",
                "arn": "arn:aws:iam::1234567890:role/sdlf-cicd-domain",
                "accountId": "1234567890",
                "userName": "sdlf-cicd-domain"
            },
            "attributes": {
                "creationDate": "2024-04-02T10:00:03Z",
                "mfaAuthenticated": "false"
            }
        },
        "invokedBy": "cloudformation.amazonaws.com"
    },
    "eventTime": "2024-04-02T10:00:03Z",
    "eventSource": "s3.amazonaws.com",
    "eventName": "CreateStorageLensGroup",
    "awsRegion": "eu-west-1",
    "sourceIPAddress": "cloudformation.amazonaws.com",
    "userAgent": "cloudformation.amazonaws.com",
    "errorCode": "AccessDenied",
    "errorMessage": "Access Denied",
    "requestParameters": {
        "Host": "1234567890.s3-control.eu-west-1.amazonaws.com",
        "CreateStorageLensGroupRequest": {
            "xmlns": "http://awss3control.amazonaws.com/doc/2018-08-20/",
            "StorageLensGroup": {
                "Filter": {
                    "MatchAnyPrefix": {
                        "Prefix": [
                            "post-stage/team/",
                            "team/",
                            "pre-stage/team/"
                        ]
                    }
                },
                "Name": "sdlf-team"
            },
            "Tags": {
                "Tag": [
                    {
                        "Value": "team",
                        "Key": "sdlf:team"
                    },
                    {
                        "Value": "sdlf",
                        "Key": "Framework"
                    }
                ]
            }
        }
    },
    "responseElements": null,
    "additionalEventData": {
        "SignatureVersion": "SigV4",
        "CipherSuite": "ECDHE-RSA-AES128-GCM-SHA256",
        "bytesTransferredIn": 463,

    },
    "requestID": "",
    "eventID": ",
    "readOnly": false,
    "eventType": "AwsApiCall",
    "managementEvent": true,
    "recipientAccountId": "1234567890",
    "eventCategory": "Management"
}
```

**To Reproduce**
Deploy SDLF enable monitoring S3 Lens like listed in the SDLF workshop additional features.

**Expected behavior**
Deploy domain without failing on s3 lens group creating due to missing permissions.

**SDLF release (if known):**
E.g. 2.2.0

**Additional context**
