### ISSUE TITLE
Adding multiple resources with same pTeamName will cause Cloudformation deployment to fail

### ISSUE THREAD

**Issue by dverdonschot** [awslabs/aws-serverless-data-lake-framework#311]
**Describe the bug**

I followed the Hitting Production part of the SDLF Workshop and wanted to add the monitoring stacks.
But when deploying the pipelines it would fail because pTeamName is defined 2 times in the team-<domain>-<team>-<environment>.yaml file.
The logic will pick up the list with 2 times the same team name for a loop (team in teams) and try to start 2 Cloudformation stacks for the same team, the second stack would fail because there was already a Cloudformation stack in the process of updating with the same name.

Example YAML with 2 times pTeamName, team-<domain>-<team>-<environment>.yaml :

```yaml
AWSTemplateFormatVersion: 2010-09-09
Description: team SDLF Team in pcteam domain, dev environment

Parameters:
    pPipelineReference:
        Type: String
        Default: none

Resources:
    rPca:
        Type: awslabs::sdlf::team::MODULE
        Properties:
            pPipelineReference: !Ref pPipelineReference
            pTeamName: team
            pEnvironment: dev
            pSNSNotificationsEmail: nobody@amazon.com
            pEnableVpc: true
            pVpcSecurityGroupIds: !ImportValue sdlf-cicd-domain-roles-vpc-security-groups
            pVpcSubnetIds: !ImportValue sdlf-cicd-domain-roles-vpc-subnets

    rPcaMonitoring:
        Type: awslabs::sdlf::monitoring::MODULE
        Properties:
            pPipelineReference: !Ref pPipelineReference
            pStorageLensEnabled: true
            pTeamName: team
```

I fixed it by updating 2 files in sdlf-cicd:
crossaccountteam-cicd/src/lambda_function.py line 265:

```python
            unique_teams = list(dict.fromkeys(teams))
            for team in unique_teams:
```
line 288 also needs the unique_teams variable.

team-cicd-lambda/src/lambda_function.py line 414:

```python
            unique_teams = list(dict.fromkeys(domain_details["teams"]))
            for team in unique_teams:
```
line 431 also needs the unique_teams variable.

After these fixes the team will be unique and only trigger each Cloudformation stack 1 time.

**To Reproduce**
Add the monitoring stacks from Other Goodies to the Hitting Production pipeline with the same pTeamName.

**Expected behavior**
The pipeline to run and update  / deploy the Cloudformation code.

**SDLF release (if known):**
SDLF 2.2.0
